//initialize the variables
let randomGameNumber = Math.random()
const userInput =  prompt("What's your choice?")
let computerChoice = ""

//check the values generated by the randomGameNumber and match it to the correct computerChoice
function getComputerChoice(){
    if(randomGameNumber <= 0.3 ){
        computerChoice = "rocks"
    }
    else if(randomGameNumber > 0.3 && randomGameNumber <= 0.6){
        computerChoice = "paper"
    }
    else if(randomGameNumber > 0.6 && randomGameNumber <= 0.9)
       { computerChoice = "scissors" }
    console.log(computerChoice) 
    return(computerChoice)
}
getComputerChoice();

//get the humanChoice through the userInput
function getHumanChoice(){
   let humanChoice = userInput
  console.log(humanChoice)
    return humanChoice;
} 
getHumanChoice();

//logic for the game to determine the winner/loser of each round
function playGame(){
let humanScore = 0;
let computerScore = 0;
let eachRound = 0;
let eachGame = 5
const humanSelection = getHumanChoice();
const computerSelection = getComputerChoice();

function playRound(humanChoice, computerChoice) {
if (humanChoice === computerChoice){
   console.log("A draw")
}
else if(humanChoice === "rocks" && computerChoice === "scissors"){
    console.log("You win. Rock beats Scissors")
    ++humanScore
}
else if(humanChoice === "scissors" && computerChoice === "paper"){
 console.log("You win. scissors beats paper")
 ++humanScore
}
else if(humanChoice === "paper" && computerChoice === "rocks"){
 console.log("You win. paper beats rocks")
 ++humanScore
}
else if (humanChoice === "scissors" && computerChoice === "rocks"){
     console.log("Computer wins. Rock beats Scissors")
    ++computerScore
}
else if(humanChoice === "paper" && computerChoice === "scissors"){
 console.log("Computer win. scissors beats paper")
 ++computerScore
}
else if(humanChoice === "rocks" && computerChoice === "paper"){
 console.log("Computer wins. paper beats rocks")
 ++computerScore
}
}
playRound(humanSelection, computerSelection);

if (eachRound <= eachGame){
 playRound(humanSelection, computerSelection);   
}
else { console.log("You've completed the game")}


if(humanScore > computerScore){
    console.log(`You win ${humanScore}`)
}
else{console.log(`Computer wins ${computerScore}`)}
}
console.log(playGame())